name: Test

on:
  push:
    branches: [ master, async ]
  pull_request:
    branches: [ master, async ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        ls -la
        cd app
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt -r requirements/prod.txt
        ls -la
        ls -la ..
        cd ../integration_tests
        pip install -r requirements.txt
    - name: Typecheck
      run: |
        export PYTHONPATH=$PWD
        ./scripts/typecheck
    - name: Lint
      run: ./scripts/lint
    - name: Test
      run: |
        docker-compose -f dev.docker-compose.yml up -d
        cd app
        python manage.py sync
        cd ..
        ./scripts/test
        docker-compose -f dev.docker-compose.yml down
